### ISSUE TITLE
Duplicate octavia-index buttons

### ISSUE THREAD

**Issue by thoyt** [OctaviaProject/portfolios#3]
We have two buttons with an id of octavia-index, and the click event only binds the non-mobile button. ;)

**Comment by MeghanMcNamara** [comment]
Good catch, TT!

On Wednesday, January 13, 2016, Tyler Hoyt notifications@github.com wrote:

> We have two buttons with an id of octavia-index, and the click event only
> binds the non-mobile button. ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OctaviaProject/portfolios/issues/3.

## 

908.246.0269
memcnama@gmail.com

**Comment by dhartunian** [comment]
This is fixed by this commit https://github.com/OctaviaProject/portfolios/commit/69c3c63cc394d4afc226165d990e7e18feba27ae

@thoyt I assume we don't have other uses for the click handler I removed...let me know if that's not the case.

**Comment by thoyt** [comment]
Def don't need the click handler now.. I didn't know those bootstrap classes worked on anchors, that's kinda nifty.

Still bugs me that we have a duplicate id but I'll let it slide.. this time..

**Comment by dhartunian** [comment]
ugh i dislike that too. removed it cause we don't even need it!
